FROM python:3.11-slim
WORKDIR /app
COPY backend/ .
COPY Database/db.sql ./Database/db.sql
RUN pip install --no-cache-dir fastapi uvicorn mysql-connector-python bcrypt python-dotenv google-genai PyPDF2 python-multipart "pydantic[email]"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]